config/routes.rb
Rails.application.routes.draw do
  resources :proyectos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "proyectos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
    validates :name, :desc, :estado, presence: {message: "Debe ingresar datos"}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: %i[ show edit update destroy ]

  # GET /proyectos or /proyectos.json
  def index

    if params[:search].present?
      #@proyectos = Proyecto.where("name like ?", "%" + params[:name] + "%").page(params[:page]).per(10)
      @proyectos = Proyecto.where("estado =?", params[:search]).page(params[:page]).per(10)
    else
      @proyectos = Proyecto.all.page(params[:page]).per(10)
      #@proyectos = Proyecto.all
    end
  end

  # GET /proyectos/1 or /proyectos/1.json
  def show
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos or /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to proyecto_url(@proyecto), notice: "Proyecto was successfully created." }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1 or /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to proyecto_url(@proyecto), notice: "Proyecto was successfully updated." }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1 or /proyectos/1.json
  def destroy
    @proyecto.destroy

    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: "Proyecto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proyecto_params
      params.require(:proyecto).permit(:name, :desc, :fecha_i, :fecha_t, :estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor proyectos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/proyectos/_form.html.erb
<%= form_with(model: proyecto) do |form| %>
  <% if proyecto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
        <% proyecto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_area :desc %>
  </div>

  <div>
    <%= form.label :fecha_i, style: "display: block" %>
    <%= form.text_field :fecha_i %>
  </div>

  <div>
    <%= form.label :fecha_t, style: "display: block" %>
    <%= form.text_field :fecha_t %>
  </div>
<!--
  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.text_field :estado %>
  </div>
-->
  <div>
    <%= form.label :estado, style: "display: block" %>
    <%select_list = ['Propuesto', 'En Progreso', 'Terminado']%>
    <%= form.select :estado, select_list, selected: 'Propuesto'%>
    <!--%=select_tag(:estado, options_for_select([['Propuesto',1],['En Progreso',2],['Terminado',3]]))%-->
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/proyectos/_proyecto.html.erb
<div id="<%= dom_id proyecto %>">
  <p>
    <strong>Name:</strong>
    <%= proyecto.name %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= proyecto.desc %>
  </p>

  <p>
    <strong>Fecha i:</strong>
    <%= proyecto.fecha_i %>
  </p>

  <p>
    <strong>Fecha t:</strong>
    <%= proyecto.fecha_t %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= proyecto.estado %>
  </p>
  <p>
    <label for="estado">Estado</label>
    <%=select_tag(:estado, options_for_select([['Propuesto',1],['En Progreso',2],['Terminado',3]]))%>
  </p>
</div>

app/views/proyectos/edit.html.erb
<h1>Editing proyecto</h1>

<%= render "form", proyecto: @proyecto %>

<br>

<div>
  <%= link_to "Show this proyecto", @proyecto %> |
  <%= link_to "Back to proyectos", proyectos_path %>
</div>

app/views/proyectos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Proyectos</h1>
<div class="container">
<nav class="navbar navbar-light bg-light">
      <form class="form-inline">
      Proyecto
      <select class="form-select" name="search" id="">
        <option value="">Todos</option>
        <option value="Propuesto">Propuesto</option>
        <option value="En Progreso">En Progreso</option>
        <option value="Terminado">Terminado</option>
      </select>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
  </div>
</nav>

<% if @proyectos.count > 0 %>
<h1>Resultados para el proyecto: <%=params[:search]%></h1>
<div id="proyectos">
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Fecha Comienzo</th>
      <th>Fecha Téermino</th>
      <th>Estado</th>
      <th>Ver Datos</th>
    </tr>
  </thead>


    <% @proyectos.each do |proyecto| %>
      <tr>
        <td><%= proyecto.name %></td>
        <td><%= proyecto.desc %></td>
        <td><%= proyecto.fecha_i %></td>
        <td><%= proyecto.fecha_t %></td>
        <td><%= proyecto.estado %></td>
        <td><%= link_to "Ver proyecto", proyecto %></td>
      </tr>
    <% end %>

  </table>
</div>
<br><br>
<%=paginate(@proyectos)%>
<br><br>

<%else%>
<h1>No hay resultados para la búsqueda <%=params[:search] %></h1>
<%end%>


<%= link_to "Nuevo proyecto", new_proyecto_path %>

</div>

app/views/proyectos/new.html.erb
<h1>New proyecto</h1>

<%= render "form", proyecto: @proyecto %>

<br>

<div>
  <%= link_to "Back to proyectos", proyectos_path %>
</div>

app/views/proyectos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @proyecto %>

<div>
  <%= link_to "Edit this proyecto", edit_proyecto_path(@proyecto) %> |
  <%= link_to "Back to proyectos", proyectos_path %>

  <%= button_to "Destroy this proyecto", @proyecto, method: :delete %>
</div>